= GitEx image:https://img.shields.io/github/actions/workflow/status/kieranpotts/gitex/integration.yaml?branch=dev&style=flat-square&label=tests&labelColor=%23333333&color=%23008800&cacheSeconds=86400[Integration tests passing]

GitEx is a suite of useful Git extensions – things like `git sync`, `git amend`, `git squash`, `git fixup`, and `git undo`.

The extensions are implemented as POSIX-compliant Unix shell scripts. To install the extensions, all you need to do is add the scripts to your operating system's `PATH` environment variable. Git will automatically integrate the scripts as https://git-scm.com/book/ms/v2/Git-Basics-Git-Aliases[Git aliases].

GitEx is inspired by TJ Holowaychuk's https://github.com/tj/git-extras[Git Extras]. But GitEx is not a fork and it is not designed to be compatible with, or a drop-in replacement for, Git Extras. Although some GitEx extensions have similar APIs to those in Git Extras, their behaviors are different. For example, GitEx's `git feature` doesn't behave in exactly the same way as Git Extras's `git feature`. It is not recommended to try to install both GitEx and Git Extras side-by-side – you should choose one or the other.

WARNING: You use these Git extensions at your own risk. Some operations enabled via these extensions are potentially destructive. For example, some of the extensions will rewrite the commit histories of your Git repositories.

== Documentation

* link:./docs/requirements.adoc[*Requirements*]
* link:./docs/installation.adoc[*Installation*]
* link:./docs/usage/README.adoc[*Usage*]
* link:./docs/testing.adoc[*Testing*]

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[MIT license]
