= Static analysis

https://github.com/koalaman/shellcheck[ShellCheck] is used for static analysis of the shell scripts. To install ShellCheck on a Debian-based system, run:

----
sudo apt-get install -y shellcheck
----

Shellcheck is already pre-installed in the dev container, if you're using that.

To run the linter on all the shell scripts in the `bin` directory, run the following command from the root directory of this repository:

----
$ shellcheck --severity=warning bin/* lib/*
----

(Other ShellCheck severity levels, in declining order of severity, are: "error", "warning", "info", and "style".)

https://github.com/astral-sh/ruff[Ruff] is used to lint and format the Python code used in the runtime tests. Installation of Ruff is managed by Poetry – see link:./runtime-tests.adoc[Runtime tests] for details.

To run Ruff, use the following commands from the root directory of this repository:

----
$ poetry run ruff check test/
$ poetry run ruff format test/
----

The formatter should be run before committing any changes to the Python test files.

[TIP]
======
Automated formatting can be applied using this shortcut:

----
$ ./fix
----

In the dev container, you will need to use the following command instead:

----
$ bash fix
----

Remember to give yourself executable privileges on this file:

----
$ chmod u+x fix
----
======
