= Testing

== Runtime tests

Execution of the runtime tests requires the following dependencies:

* Python >= 3.12
* Poetry >= 2.2

https://github.com/python-poetry/poetry[Poetry] is used to manage the Python dependencies for the GitEx project. Run `poetry install` in the root directory of this repository to install the dependencies in a virtual environment.

The tests are run by https://github.com/pytest-dev/pytest/[pytest]. To execute the tests, run the following command from the root directory of the repository:

[source]
----
$ poetry run pytest
----

Or, for more verbose output:

[source]
----
$ poetry run pytest -v
----

The tests use https://github.com/gitpython-developers/GitPython[Git Python] to dynamically create temporary Git repositories, and the tests do not change any global, system-level, or user-level Git configuration, ensuring isolation and no interference with your own Git configuration.

== Static analysis

https://github.com/koalaman/shellcheck[ShellCheck] is used for static analysis of the shell scripts. To install ShellCheck on a Debian-based system, run:

[source]
----
sudo apt-get install -y shellcheck
----

To run the linter on all the shell scripts in the `bin` directory, run the following command from the root directory of the repository:

[source]
----
$ shellcheck --severity=error bin/* lib/*
----

https://github.com/astral-sh/ruff[Ruff] is used to lint and format the Python code used in the runtime tests. Installation of Ruff is managed by Poetry (see above). To run Ruff, use the following commands from the root directory of the repository:

[source]
----
$ poetry run ruff check test/
$ poetry run ruff format test/
----

The formatter should be run before committing any changes to the Python test files.
