= `git br`

Create a new branch from the current HEAD position, switch to it, and immediately push it to the remote with tracking established.

This command combines three operations into one:

1. Create a new branch from current position (`git branch <name>`)
2. Switch to the new branch (`git checkout <name>`)
3. Push to the remote and set up tracking (`git push --set-upstream origin HEAD`)

== Usage

----
$ git br [<branch>]
----

If no branch name is provided, you will be prompted to enter one interactively.

The operation will fail if the specified branch name already exists.

== Configuration

By default, when the new local branch is created, `git br` will automatically push the branch to the default upstream repository and sets up tracking with the pushed branch. The name of the default remote repository is assumed to be "origin", as per Git's conventions:

----
$ git push --set-upstream origin HEAD
----

If you use a different naming convention for your upstream repositories, you can set an environment variable named `X_GITEX_DEFAULT_REMOTE_NAME` to tell GitEx what it is. For example, if you use the name "upstream" instead, set this in your shell configuration file (~/.bashrc, ~/.zshrc, etc.):

----
$ export X_GITEX_DEFAULT_REMOTE_NAME=upstream
----

Now, `git br` will push new branches to the remote named "upstream" instead of "origin":

----
$ git br my-branch
----

All GitEx commands will assume your default remote is named "upstream", across all your local repositories. If yuo need to further override this default on a case-by-case basis, you will need to override the variable for individual `git br` commands:

----
$ X_GITEX_DEFAULT_REMOTE_NAME=upstream git br my-feature
----

Most Git users stick with Git's default name for remote repositories – "origin" – so it is not expected many users will need to adjust this configuration. But it's there if you need it.

== Examples

Create a new feature branch and push it:

----
$ git br feature/user-authentication
----

Create a branch interactively:

----
$ git br
Enter branch name:
> my-feature
----

== See also

* https://git-scm.com/docs/git-branch[git-branch]
* https://git-scm.com/docs/git-checkout[git-checkout]
* https://git-scm.com/docs/git-push[git-push]
