name: Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Run static analysis checks
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository and fetch its full log history.
      # https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: files
        run: |
          CHANGED_FILES=$(git diff --name-only "${BASE_SHA:-$BEFORE_SHA}...${HEAD_SHA:-$GITHUB_REF}")
          echo "::notice::Changed files: $CHANGED_FILES"
          {
            echo "added_modified<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          BEFORE_SHA: "${{ github.event.before }}"

      - name: Shellcheck
        run: shellcheck --severity=error bin/* lib/*

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install EditorConfig checker
        run: go install 'github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@latest'

      - name: Run EditorConfig checker
        run: echo "$FILES" | xargs ~/go/bin/editorconfig-checker
        env:
          FILES: "${{ steps.files.outputs.added_modified }}"
